FROM node:16-alpine AS build

LABEL maintainer="info@cert.pl"

COPY ./mwdb/web /app
COPY ./docker/plugins /app/plugins

ARG web_plugins
RUN cd /app \
    && npm install --unsafe-perm . $web_plugins $(find /app/plugins -name 'package.json' -exec dirname {} \; | sort -u) \
    && CI=true npm run build \
    && npm cache clean --force

ENV PROXY_BACKEND_URL http://mwdb.:8080

WORKDIR /app
CMD ["npm", "run", "dev"]
