FROM node:16-alpine AS build

LABEL maintainer="info@cert.pl"

COPY ./mwdb/web /app
COPY ./docker/plugins /app/plugins

ARG web_plugins
RUN cd /app \
    && npm install --unsafe-perm . $web_plugins $(find /app/plugins -name 'package.json' -exec dirname {} \; | sort -u) \
    && CI=true npm run build \
    && npm cache clean --force

FROM nginx:stable

LABEL maintainer="info@cert.pl"

ENV PROXY_BACKEND_URL http://mwdb.:8080
ENV NGINX_MAX_UPLOAD_SIZE 50M

COPY docker/nginx.conf.template /etc/nginx/templates/default.conf.template
COPY --from=build /app/dist /usr/share/nginx/html

# Give +r to everything in /usr/share/nginx/html and +x for directories
RUN chmod u=rX,go= -R /usr/share/nginx/html

# By default everything is owned by root - change owner to nginx
RUN chown nginx:nginx -R /usr/share/nginx/html
