FROM python:3.8.5-alpine

COPY docker/OIDC /oidc

RUN apk add gcc g++ musl-dev python3-dev libffi-dev openssl-dev cargo

COPY docker/OIDC/requirements.txt requirements.txt

RUN pip install -r requirements.txt

ENV AUTHLIB_INSECURE_TRANSPORT=1

ENV FLASK_APP=/oidc/website/run.py

WORKDIR /oidc

CMD ["flask", "run"]
