"""empty message

Revision ID: 025b1d5b7bba
Revises: 99a65693c6cc
Create Date: 2018-11-22 19:28:39.889995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '025b1d5b7bba'
down_revision = '6ae8b29bf051'
branch_labels = None
depends_on = None

permissions = [
    'manage_users',
    'share_queried_objects',
    'access_all_objects',
    'sharing_objects',
    'adding_tags',
    'removing_tags',
    'adding_comments',
    'removing_comments',
    'adding_parents',
    'reading_attributes',
    'adding_attributes',
    'managing_attributes',
    'reading_blobs',
    'adding_blobs'
]


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION pg_trgm;')

    op.create_table('text_blob',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blob_name', sa.String(), nullable=True),
    sa.Column('blob_size', sa.Integer(), nullable=False),
    sa.Column('blob_type', sa.String(length=32), nullable=True),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['object.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_text_blob_blob_name'), 'text_blob', ['blob_name'], unique=False)
    op.create_index(op.f('ix_text_blob_blob_size'), 'text_blob', ['blob_size'], unique=False)
    op.create_index(op.f('ix_text_blob_blob_type'), 'text_blob', ['blob_type'], unique=False)
    op.create_index(op.f('ix_text_blob_last_seen'), 'text_blob', ['last_seen'], unique=False)

    op.execute('CREATE INDEX trgm_idx_text_blob_content ON text_blob USING gin (content gin_trgm_ops);')

    op.execute('ALTER TYPE group_capabilities RENAME TO group_capabilities_old;')
    op.execute('CREATE TYPE group_capabilities AS ENUM({});'.format(
        ', '.join(list(map(lambda s: "'{}'".format(s), permissions)))))
    op.execute('ALTER TABLE "group" ALTER COLUMN capabilities TYPE group_capabilities[] '
               'USING capabilities::text::group_capabilities[];')
    op.execute('DROP TYPE group_capabilities_old;')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP INDEX trgm_idx_text_blob_content;')

    op.drop_index(op.f('ix_text_blob_last_seen'), table_name='text_blob')
    op.drop_index(op.f('ix_text_blob_blob_type'), table_name='text_blob')
    op.drop_index(op.f('ix_text_blob_blob_size'), table_name='text_blob')
    op.drop_index(op.f('ix_text_blob_blob_name'), table_name='text_blob')
    op.drop_table('text_blob')

    op.execute('UPDATE "group" SET capabilities = array_remove(capabilities, \'reading_blobs\');')
    op.execute('UPDATE "group" SET capabilities = array_remove(capabilities, \'adding_blobs\');')
    op.execute('ALTER TYPE group_capabilities RENAME TO group_capabilities_old;')
    op.execute('CREATE TYPE group_capabilities AS ENUM({});'.format(
        ', '.join(list(map(lambda s: "'{}'".format(s), permissions[:-2])))))
    op.execute('ALTER TABLE "group" ALTER COLUMN capabilities TYPE group_capabilities[] '
               'USING capabilities::text::group_capabilities[];')
    op.execute('DROP TYPE group_capabilities_old;')
    # ### end Alembic commands ###
