"""empty message

Revision ID: 0c0231128363
Revises: 8ac8c65a83ee
Create Date: 2019-10-24 20:49:55.842313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c0231128363'
down_revision = '8ac8c65a83ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_permission_related_user_id'), 'permission', ['related_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_permission_related_user_id'), table_name='permission')
    # ### end Alembic commands ###
