"""empty message

Revision ID: 14d21382f7e1
Revises: 462a7481563f
Create Date: 2019-03-12 18:08:30.454868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14d21382f7e1'
down_revision = '462a7481563f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.add_column('group', sa.Column('private', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('disabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'disabled')
    op.drop_column('group', 'private')
    op.drop_table('member')
    # ### end Alembic commands ###
