"""empty message

Revision ID: 184243329483
Revises: 5adeaea4045d
Create Date: 2018-10-19 15:55:11.295625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '184243329483'
down_revision = '5adeaea4045d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('additional_info', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'additional_info')
    # ### end Alembic commands ###
