"""empty message

Revision ID: 2e692ea445a1
Revises: 7698f0bebad7
Create Date: 2020-05-11 16:36:48.199874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e692ea445a1'
down_revision = '7698f0bebad7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'metakey_definition',
        sa.Column('hidden', sa.Boolean(), nullable=True)
    )
    op.execute("UPDATE metakey_definition SET hidden = false")
    op.alter_column('metakey_definition', 'hidden', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metakey_definition', 'hidden')
    # ### end Alembic commands ###
