"""empty message

Revision ID: 2fdb9b803b80
Revises: 
Create Date: 2018-09-18 15:03:49.905669

"""
from alembic import op
import sqlalchemy as sa

import re
from model import db


# http://docs.sqlalchemy.org/en/latest/dialects/postgresql.html?highlight=using%20enum%20array#using-enum-with-array
class ArrayOfEnum(sa.ARRAY):
    def bind_expression(self, bindvalue):
        return db.cast(bindvalue, self)

    def result_processor(self, dialect, coltype):
        super_rp = super(ArrayOfEnum, self).result_processor(
            dialect, coltype)

        def handle_raw_string(value):
            inner = re.match(r"^{(.*)}$", value).group(1)
            return inner.split(",") if inner else []

        def process(value):
            if value is None:
                return None
            return super_rp(handle_raw_string(value))

        return process


# revision identifiers, used by Alembic.
revision = '2fdb9b803b80'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('capabilities', ArrayOfEnum(sa.Enum('manage_users', 'share_queried_objects', 'access_all_objects', 'sharing_objects', 'adding_tags', 'removing_tags', 'adding_comments', 'removing_comments', 'adding_parents', 'reading_attributes', 'adding_attributes', 'managing_attributes', name='group_capabilities')), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_group_name'), 'group', ['name'], unique=True)
    op.create_table('metakey_definition',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('url_template', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('object',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('dhash', sa.String(length=64), nullable=True),
    sa.Column('upload_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_object_dhash'), 'object', ['dhash'], unique=True)
    op.create_index(op.f('ix_object_upload_time'), 'object', ['upload_time'], unique=False)
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_tag'), 'tag', ['tag'], unique=True)
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.Text(), nullable=True),
    sa.Column('md5', sa.String(length=32), nullable=False),
    sa.Column('crc32', sa.String(length=8), nullable=False),
    sa.Column('sha1', sa.String(length=40), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('sha512', sa.String(length=128), nullable=False),
    sa.Column('humanhash', sa.String(), nullable=False),
    sa.Column('ssdeep', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['object.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_crc32'), 'file', ['crc32'], unique=False)
    op.create_index(op.f('ix_file_file_name'), 'file', ['file_name'], unique=False)
    op.create_index(op.f('ix_file_file_size'), 'file', ['file_size'], unique=False)
    op.create_index(op.f('ix_file_file_type'), 'file', ['file_type'], unique=False)
    op.create_index(op.f('ix_file_humanhash'), 'file', ['humanhash'], unique=False)
    op.create_index(op.f('ix_file_md5'), 'file', ['md5'], unique=False)
    op.create_index(op.f('ix_file_sha1'), 'file', ['sha1'], unique=False)
    op.create_index(op.f('ix_file_sha256'), 'file', ['sha256'], unique=True)
    op.create_index(op.f('ix_file_sha512'), 'file', ['sha512'], unique=False)
    op.create_index(op.f('ix_file_ssdeep'), 'file', ['ssdeep'], unique=False)
    op.create_table('metakey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=64), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['key'], ['metakey_definition.key'], ),
    sa.ForeignKeyConstraint(['object_id'], ['object.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_id', 'key', 'value')
    )
    op.create_index(op.f('ix_metakey_key'), 'metakey', ['key'], unique=False)
    op.create_index(op.f('ix_metakey_value'), 'metakey', ['value'], unique=False)
    op.create_table('object_tag',
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['object_id'], ['object.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    op.create_table('permission',
    sa.Column('object_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('group_name', sa.String(length=32), autoincrement=False, nullable=False),
    sa.Column('access_time', sa.DateTime(), nullable=False),
    sa.Column('access_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['group_name'], ['group.name'], ),
    sa.ForeignKeyConstraint(['object_id'], ['object.id'], ),
    sa.PrimaryKeyConstraint('object_id', 'group_name')
    )
    op.create_index(op.f('ix_permission_access_time'), 'permission', ['access_time'], unique=False)
    op.create_table('relation',
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('child_id', sa.Integer(), nullable=True),
    sa.Column('creation_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['object.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['object.id'], )
    )
    op.create_table('static_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family', sa.String(length=32), nullable=True),
    sa.Column('cfg', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['object.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_static_config_family'), 'static_config', ['family'], unique=False)
    op.create_table('user',
    sa.Column('login', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('version_uid', sa.String(length=16), nullable=True),
    sa.Column('group_name', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['group_name'], ['group.name'], ),
    sa.PrimaryKeyConstraint('login')
    )
    op.create_index(op.f('ix_user_login'), 'user', ['login'], unique=True)
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('user_login', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['object_id'], ['object.id'], ),
    sa.ForeignKeyConstraint(['user_login'], ['user.login'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    op.drop_index(op.f('ix_user_login'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_static_config_family'), table_name='static_config')
    op.drop_table('static_config')
    op.drop_table('relation')
    op.drop_index(op.f('ix_permission_access_time'), table_name='permission')
    op.drop_table('permission')
    op.drop_table('object_tag')
    op.drop_index(op.f('ix_metakey_value'), table_name='metakey')
    op.drop_index(op.f('ix_metakey_key'), table_name='metakey')
    op.drop_table('metakey')
    op.drop_index(op.f('ix_file_ssdeep'), table_name='file')
    op.drop_index(op.f('ix_file_sha512'), table_name='file')
    op.drop_index(op.f('ix_file_sha256'), table_name='file')
    op.drop_index(op.f('ix_file_sha1'), table_name='file')
    op.drop_index(op.f('ix_file_md5'), table_name='file')
    op.drop_index(op.f('ix_file_humanhash'), table_name='file')
    op.drop_index(op.f('ix_file_file_type'), table_name='file')
    op.drop_index(op.f('ix_file_file_size'), table_name='file')
    op.drop_index(op.f('ix_file_file_name'), table_name='file')
    op.drop_index(op.f('ix_file_crc32'), table_name='file')
    op.drop_table('file')
    op.drop_index(op.f('ix_tag_tag'), table_name='tag')
    op.drop_table('tag')
    op.drop_index(op.f('ix_object_upload_time'), table_name='object')
    op.drop_index(op.f('ix_object_dhash'), table_name='object')
    op.drop_table('object')
    op.drop_table('metakey_definition')
    op.drop_index(op.f('ix_group_name'), table_name='group')
    op.drop_table('group')
    # ### end Alembic commands ###
