"""empty message

Revision ID: 426a27b8e97c
Revises: 0c0231128363
Create Date: 2019-12-16 18:35:47.804621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '426a27b8e97c'
down_revision = '0c0231128363'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metakey_permission',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('group_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('can_read', sa.Boolean(), nullable=False),
    sa.Column('can_set', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['key'], ['metakey_definition.key'], ),
    sa.PrimaryKeyConstraint('key', 'group_id')
    )
    op.create_index(op.f('ix_metakey_permission_group_id'), 'metakey_permission', ['group_id'], unique=False)
    op.create_index(op.f('ix_metakey_permission_key'), 'metakey_permission', ['key'], unique=False)
    op.create_index('ix_metakey_permission_metakey_group', 'metakey_permission', ['key', 'group_id'], unique=True)
    op.add_column('metakey_definition', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('metakey_definition', sa.Column('label', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metakey_definition', 'label')
    op.drop_column('metakey_definition', 'description')
    op.drop_index('ix_metakey_permission_metakey_group', table_name='metakey_permission')
    op.drop_index(op.f('ix_metakey_permission_key'), table_name='metakey_permission')
    op.drop_index(op.f('ix_metakey_permission_group_id'), table_name='metakey_permission')
    op.drop_table('metakey_permission')
    # ### end Alembic commands ###
