"""empty message

Revision ID: 8ba9c7aa6c68
Revises: e7703e6faca5
Create Date: 2019-08-28 15:46:59.596289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ba9c7aa6c68'
down_revision = 'b9fe41d39b94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pending', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('requested_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'requested_on')
    op.drop_column('user', 'pending')
    # ### end Alembic commands ###
