"""empty message

Revision ID: 9ec11b7b5365
Revises: 78ec1a99bbc4
Create Date: 2019-03-20 14:58:13.198516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ec11b7b5365'
down_revision = '78ec1a99bbc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('logged_on', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('registered_by', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('registered_on', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('set_password_on', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'user', 'user', ['registered_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'set_password_on')
    op.drop_column('user', 'registered_on')
    op.drop_column('user', 'registered_by')
    op.drop_column('user', 'logged_on')
    # ### end Alembic commands ###
