"""empty message

Revision ID: b9fe41d39b94
Revises: e7703e6faca5
Create Date: 2019-09-02 19:12:52.798200

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b9fe41d39b94'
down_revision = 'e7703e6faca5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('issued_on', sa.DateTime(), nullable=True),
    sa.Column('issued_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['issued_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('identity_ver', sa.String(length=16), nullable=True))
    op.add_column('user', sa.Column('password_ver', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_ver')
    op.drop_column('user', 'identity_ver')
    op.drop_table('api_key')
    # ### end Alembic commands ###
