"""empty message

Revision ID: e7703e6faca5
Revises: 7cdbdf47aa82
Create Date: 2019-08-19 18:16:32.917140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7703e6faca5'
down_revision = '7cdbdf47aa82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # FIXME WTF
    #op.drop_index('trgm_idx_text_blob_content', table_name='text_blob')
    op.add_column('user', sa.Column('feed_quality', sa.String(length=32), server_default='high', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'feed_quality')
    #op.create_index('trgm_idx_text_blob_content', 'text_blob', ['content'], unique=False)
    # ### end Alembic commands ###
