services:
  mwdb:
    environment:
      MWDB_ENABLE_KARTON: 1
    depends_on:
      karton-system-router:
        condition: service_started
    volumes:
      - "./dev/karton.ini:/etc/karton/karton.ini"
  karton-system-router:
    image: certpl/karton-system:v5.9.0
    depends_on:
      minio:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./config/karton.docker.ini:/etc/karton/karton.ini
    entrypoint: karton-system
    command: --setup-bucket --disable-gc
  karton-system-gc:
    image: certpl/karton-system:v5.9.0
    depends_on:
      karton-system-router:
        condition: service_started
    volumes:
      - ./config/karton.docker.ini:/etc/karton/karton.ini
    entrypoint: karton-system
    command: --disable-router
  karton-classifier:
    image: certpl/karton-classifier:v2.1.0
    depends_on:
      - redis
      - minio
    volumes:
      - "./dev/karton.ini:/etc/karton/karton.ini"
  karton-dashboard:
    image: certpl/karton-dashboard:v1.6.0
    depends_on:
      - redis
      - minio
    volumes:
      - "./dev/karton.ini:/etc/karton/karton.ini"
    ports:
      - "127.0.0.1:8030:5000"
  karton-mwdb-reporter:
    image: certpl/karton-mwdb-reporter:v1.3.0
    depends_on:
      - redis
      - minio
      - mwdb-web
      - mwdb
    volumes:
      - "./dev/karton.ini:/etc/karton/karton.ini"
    env_file:
      - mwdb-vars.env
