"""Object deletion improvements - cascades and related_object_id index

Revision ID: 01dea56ffaf7
Revises: 6745a530097e
Create Date: 2026-04-10 13:36:56.534504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01dea56ffaf7'
down_revision = '6745a530097e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attribute', schema=None) as batch_op:
        batch_op.drop_constraint('attribute_object_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'object', ['object_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint('favorites_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorites_object_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'object', ['object_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('karton_object', schema=None) as batch_op:
        batch_op.drop_constraint('karton_object_object_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('karton_object_analysis_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'object', ['object_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'karton_analysis', ['analysis_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permission_related_object_id'), ['related_object_id'], unique=False)
        batch_op.drop_constraint('permission_related_object_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'object', ['related_object_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('relation', schema=None) as batch_op:
        batch_op.drop_constraint('relation_parent_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('relation_child_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'object', ['child_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'object', ['parent_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('relation_child_id_fkey', 'object', ['child_id'], ['id'])
        batch_op.create_foreign_key('relation_parent_id_fkey', 'object', ['parent_id'], ['id'])

    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('permission_related_object_id_fkey', 'object', ['related_object_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_permission_related_object_id'))

    with op.batch_alter_table('karton_object', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('karton_object_analysis_id_fkey', 'karton_analysis', ['analysis_id'], ['id'])
        batch_op.create_foreign_key('karton_object_object_id_fkey', 'object', ['object_id'], ['id'])

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorites_object_id_fkey', 'object', ['object_id'], ['id'])
        batch_op.create_foreign_key('favorites_user_id_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('attribute', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('attribute_object_id_fkey', 'object', ['object_id'], ['id'])

    # ### end Alembic commands ###
