"""Add index on comment.object_id

Revision ID: 2c44b2073670
Revises: 72a94f88d2b6
Create Date: 2024-10-04 15:52:04.736269

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2c44b2073670"
down_revision = "72a94f88d2b6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_comment_object_id"), "comment", ["object_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_comment_object_id"), table_name="comment")
    # ### end Alembic commands ###
