"""Index 'object.cfg' column using GIN index

Revision ID: 3962c4e3f4ff
Revises: 6a7aefae72d3
Create Date: 2024-01-10 15:48:17.061253

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "3962c4e3f4ff"
down_revision = "6a7aefae72d3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_object_cfg", "object", ["cfg"], unique=False, postgresql_using="gin"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_object_cfg", table_name="object")
    # ### end Alembic commands ###
