"""Add quick query model

Revision ID: 43b78a070936
Revises: 3e2203dea478
Create Date: 2020-07-31 15:39:16.595524

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "43b78a070936"
down_revision = "3e2203dea478"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quick_query",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("query", sa.Text(), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("quick_query")
    # ### end Alembic commands ###
