"""add alt_names column to File

Revision ID: 4b0733973847
Revises: 243dede4eb74
Create Date: 2021-11-04 12:57:30.836900

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "4b0733973847"
down_revision = "243dede4eb74"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "file",
        sa.Column(
            "alt_names",
            postgresql.ARRAY(sa.String()),
            server_default="{}",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("file", "alt_names")
    # ### end Alembic commands ###
