"""Add index on comment.user_id

Revision ID: 52bb55f76ef3
Revises: 2c44b2073670
Create Date: 2024-10-18 10:36:52.350767

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "52bb55f76ef3"
down_revision = "2c44b2073670"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_comment_user_id"), "comment", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_comment_user_id"), table_name="comment")
    # ### end Alembic commands ###
