"""Removed User.version_uid column

Revision ID: 56adf974831e
Revises: 52bb55f76ef3
Create Date: 2024-12-11 18:21:42.442984

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "56adf974831e"
down_revision = "52bb55f76ef3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "version_uid")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "version_uid", sa.VARCHAR(length=16), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
