"""Add 'openid_provider.requires_approval' field

Revision ID: 6745a530097e
Revises: 52bb55f76ef3
Create Date: 2026-02-05 14:56:39.156847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6745a530097e'
down_revision = '52bb55f76ef3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('openid_provider', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requires_approval', sa.Boolean(), nullable=True))

    op.execute("UPDATE openid_provider SET requires_approval=false;")

    with op.batch_alter_table('openid_provider', schema=None) as batch_op:
        batch_op.alter_column(sa.Column('requires_approval', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('openid_provider', schema=None) as batch_op:
        batch_op.drop_column('requires_approval')
    # ### end Alembic commands ###
