"""Not null on associative tables

Revision ID: 6fd822d1d706
Revises: 12849e43c922
Create Date: 2021-02-04 14:34:24.251808

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6fd822d1d706"
down_revision = "12849e43c922"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "object_tag", "object_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column("object_tag", "tag_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("relation", "child_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("relation", "parent_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("relation", "parent_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("relation", "child_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("object_tag", "tag_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "object_tag", "object_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
