"""Add_openid_identity

Revision ID: 7286ae5bf1b1
Revises: 7a4637519955
Create Date: 2021-08-31 12:53:49.737426

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7286ae5bf1b1"
down_revision = "7a4637519955"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "openid_identity",
        sa.Column("sub_id", sa.Integer(), nullable=False),
        sa.Column("provider_id", sa.Integer(), autoincrement=True, nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["openid_provider.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("sub_id"),
    )
    op.create_index(
        op.f("ix_openid_identity_provider_id"),
        "openid_identity",
        ["provider_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_openid_identity_provider_id"), table_name="openid_identity")
    op.drop_table("openid_identity")
    # ### end Alembic commands ###
