"""OpenID tables

Revision ID: 769c06a5f62c
Revises: 3648d869ef45
Create Date: 2021-09-06 12:37:40.325947

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "769c06a5f62c"
down_revision = "7054c09d10ac"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "openid_provider",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("client_id", sa.String(length=64), nullable=False),
        sa.Column("client_secret", sa.String(length=64), nullable=False),
        sa.Column("authorization_endpoint", sa.String(length=128), nullable=False),
        sa.Column("token_endpoint", sa.String(length=128), nullable=False),
        sa.Column("userinfo_endpoint", sa.String(length=128), nullable=False),
        sa.Column("jwks_endpoint", sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "openid_identity",
        sa.Column("sub_id", sa.Integer(), nullable=False),
        sa.Column("provider_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["openid_provider.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("sub_id"),
    )
    op.create_index(
        op.f("ix_openid_identity_provider_id"),
        "openid_identity",
        ["provider_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_openid_identity_provider_id"), table_name="openid_identity")
    op.drop_table("openid_identity")
    op.drop_table("openid_provider")
    # ### end Alembic commands ###
