"""OpenID tables

Revision ID: 7a4637519955
Revises: 4f0405411201
Create Date: 2021-07-22 16:32:03.393774

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7a4637519955"
down_revision = "3648d869ef45"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "openid_provider",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("client_id", sa.String(length=64), nullable=False),
        sa.Column("client_secret", sa.String(length=64), nullable=False),
        sa.Column("authorization_endpoint", sa.String(length=128), nullable=False),
        sa.Column("token_endpoint", sa.String(length=128), nullable=False),
        sa.Column("userinfo_endpoint", sa.String(length=128), nullable=False),
        sa.Column("jwks_endpoint", sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("openid_provider")
    # ### end Alembic commands ###
