"""Add group oidc provider

Revision ID: 7nsxysyisgrc
Revises: 6745a530097e
Create Date: 2026-02-24 10:36:52.350767

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7nsxysyisgrc"
down_revision = "6745a530097e"
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("group", sa.Column("openid_provider_name", sa.String(64), nullable=True))
    op.create_foreign_key(
        None, "group", "openid_provider", ["openid_provider_name"], ["name"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "group", type_="foreignkey")
    op.drop_column("group", "openid_provider_name")
    # ### end Alembic commands ###