"""Add group oidc provider

Revision ID: 7nsxysyisgrc
Revises: 6745a530097e
Create Date: 2026-02-24 10:36:52.350767

"""
import sqlalchemy as sa
from alembic import op

from mwdb.model import OpenIDGroupManagementMode

# revision identifiers, used by Alembic.
revision = "7nsxysyisgrc"
down_revision = "6745a530097e"
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("group", sa.Column("openid_provider_id", sa.Integer, nullable=True))
    op.create_foreign_key(
        None, "group", "openid_provider", ["openid_provider_id"], ["id"], ondelete="SET NULL"
    )

    op.execute(
        "CREATE TYPE openidgroupmanagementmode AS ENUM ('NONE', 'FULL', 'MIXED');"
    )

    op.add_column("openid_provider", sa.Column("oidc_groups_management_mode", sa.Enum(OpenIDGroupManagementMode), nullable=False))
    op.add_column("openid_provider", sa.Column("oidc_groups_match_pattern", sa.Text(), nullable=False))
    op.add_column("openid_provider", sa.Column("oidc_groups_replace_pattern", sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "group", type_="foreignkey")
    op.drop_column("group", "openid_provider_id")

    op.drop_column("openid_provider", "oidc_groups_management_mode")
    op.drop_column("openid_provider", "oidc_groups_match_pattern")
    op.drop_column("openid_provider", "oidc_groups_replace_pattern")
    # ### end Alembic commands ###