"""Drop legacy 'version_uid'

Revision ID: 80710f93fcd4
Revises: 4f0405411201
Create Date: 2021-07-20 16:00:26.347067

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "80710f93fcd4"
down_revision = "4f0405411201"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "version_uid")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "version_uid", sa.VARCHAR(length=16), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
