"""Set GIN index on cfg and alt_names columns

Revision ID: a81513c2a4bf
Revises: 6a7aefae72d3
Create Date: 2024-02-06 16:26:09.654072

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "a81513c2a4bf"
down_revision = "6a7aefae72d3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_object_alt_names",
        "object",
        ["alt_names"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_object_cfg", "object", ["cfg"], unique=False, postgresql_using="gin"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_object_cfg", table_name="object")
    op.drop_index("ix_object_alt_names", table_name="object")
    # ### end Alembic commands ###
