"""Add group_admin column to member table

Revision ID: bbd63c67663c
Revises: 43b78a070936
Create Date: 2020-09-16 15:48:39.096611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbd63c67663c'
down_revision = 'e2d99ffcb8ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('group_admin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'group_admin')
    # ### end Alembic commands ###
