"""Add index on ObjectPermission.related_object_id

Revision ID: c3e1c7543a90
Revises: 6745a530097e
Create Date: 2026-04-07 13:12:01.165718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3e1c7543a90'
down_revision = '6745a530097e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permission_related_object_id'), ['related_object_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permission_related_object_id'))
    # ### end Alembic commands ###
