"""immutable_group

Revision ID: cdae4e840ceb
Revises: 6db157d09a30
Create Date: 2022-09-15 10:24:44.498960

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cdae4e840ceb"
down_revision = "6db157d09a30"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("group", sa.Column("immutable", sa.Boolean(), nullable=True))
    op.execute(
        'UPDATE "group" SET "immutable" = CASE '
        "WHEN name = 'public' OR private = TRUE THEN TRUE "
        "ELSE FALSE "
        "END"
    )
    op.alter_column("group", "immutable", existing_type=sa.Boolean(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("group", "immutable")
    # ### end Alembic commands ###
