"""Removed humanhash feature

Revision ID: e2d99ffcb8ce
Revises: 43b78a070936
Create Date: 2020-09-10 15:51:17.133654

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e2d99ffcb8ce"
down_revision = "43b78a070936"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_file_humanhash", table_name="file")
    op.drop_column("file", "humanhash")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "file",
        sa.Column("humanhash", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.create_index("ix_file_humanhash", "file", ["humanhash"], unique=False)
    # ### end Alembic commands ###
