"""Add builtin group column

Revision ID: f004f4874bd6
Revises: c8ba40a69421
Create Date: 2021-03-26 17:42:34.022562

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.sql import expression

# revision identifiers, used by Alembic.
revision = "f004f4874bd6"
down_revision = "c8ba40a69421"
branch_labels = None
depends_on = None


def upgrade():
    # Create builtin column, set 'public' as builtin
    op.add_column(
        "group",
        sa.Column(
            "builtin", sa.Boolean(), nullable=False, server_default=expression.false()
        ),
    )
    op.execute('UPDATE "group" SET builtin=TRUE WHERE "group".name = \'public\'')
    op.alter_column("group", "builtin", nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("group", "builtin")
    # ### end Alembic commands ###
