"""Relation groups users to permissions

Revision ID: fd749df2e921
Revises: f4ccb4be2170
Create Date: 2021-04-13 12:52:43.838546

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "fd749df2e921"
down_revision = "f4ccb4be2170"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("permission_object_id_fkey", "permission", type_="foreignkey")
    op.drop_constraint("permission_group_id_fkey", "permission", type_="foreignkey")
    op.create_foreign_key(
        None, "permission", "object", ["object_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "permission", "group", ["group_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "permission", type_="foreignkey")
    op.drop_constraint(None, "permission", type_="foreignkey")
    op.create_foreign_key(
        "permission_group_id_fkey", "permission", "group", ["group_id"], ["id"]
    )
    op.create_foreign_key(
        "permission_object_id_fkey", "permission", "object", ["object_id"], ["id"]
    )
    # ### end Alembic commands ###
